language: node_js
node_js:
  - "8"

sudo: false

branches:
  only:
  - master
  - development
  - patch

install:
  - yarn

script:
  - yarn test
  - yarn build

cache:
  yarn: true
  directories:
    - ".eslintcache"
    - "node_modules"

deploy:
  - provider: script
    skip_cleanup: true
    script:
      - npx semantic-release
    on:
      branch: development

  - provider: pages
    skip-cleanup: true
    target-branch: gh-pages
    local-dir: dist
    github-token: $GITHUB_TOKEN
    on:
      branch: development