import Vue from 'vue'
Vue.component('angle-down', () => import('./angle-down.vue'))
Vue.component('angle-up', () => import('./angle-up.vue'))
Vue.component('arrow-down', () => import('./arrow-down.vue'))
Vue.component('arrow-left', () => import('./arrow-left.vue'))
Vue.component('arrow-right', () => import('./arrow-right.vue'))
Vue.component('check-mark-bold', () => import('./check-mark-bold.vue'))
Vue.component('check-mark', () => import('./check-mark.vue'))
Vue.component('close', () => import('./close.vue'))
Vue.component('credit-card', () => import('./credit-card.vue'))
Vue.component('lastschrift', () => import('./lastschrift.vue'))
Vue.component('minus', () => import('./minus.vue'))
Vue.component('phone', () => import('./phone.vue'))
Vue.component('plus', () => import('./plus.vue'))
Vue.component('print', () => import('./print.vue'))
  
